import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <nav>
            <a href="/">Home</a> | <a href="/boardgames">Board Games</a>
          </nav>
          {children}
        </Providers>
      </body>
    </html>
  );
}
